# Generated by Django 2.2.6 on 2019-11-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
    ]
