# Generated by Django 2.2.6 on 2019-11-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airwave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariffplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, unique=True)),
                ('billing_type', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('download_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('download_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'TariffPlan',
                'managed': False,
            },
        ),
    ]
