# Generated by Django 2.2.6 on 2019-11-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airwave', '0002_tariffplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('billing_address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_address_line3', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_address_pincode', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('installation_address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('installation_address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('installation_address_line3', models.CharField(blank=True, max_length=50, null=True)),
                ('installation_address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('installation_address_pincode', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('mobile2', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('landline', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('connectivity_device', models.CharField(blank=True, max_length=50, null=True)),
                ('active_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('allocated_ip', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=25, null=True)),
                ('parent_customer_id', models.IntegerField(blank=True, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Isp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ISP',
                'managed': False,
            },
        ),
    ]
