# Generated by Django 2.2.6 on 2019-11-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airwave', '0004_airwaveconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'Operator',
                'managed': False,
            },
        ),
    ]
