# Generated by Django 2.2.6 on 2019-12-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airwave', '0007_auto_20191209_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirwirePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'airwire_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbnlPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'bbnl_payment',
                'managed': False,
            },
        ),
    ]
