# Generated by Django 2.2.6 on 2019-12-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airwave', '0008_airwirepayment_bbnlpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirwirePaymentLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'airwire_payment_load',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbnlPaymentLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'bbnl_payment_load',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=20, null=True)),
                ('collection_person', models.CharField(blank=True, max_length=20, null=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cheque_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('online_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('paytm_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=25, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('online_portal', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'cash_collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=2)),
                ('instrument_number', models.CharField(blank=True, max_length=25, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('bill_number', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AirwirePayment',
        ),
        migrations.DeleteModel(
            name='BbnlPayment',
        ),
    ]
