# Generated by Django 2.2.6 on 2019-12-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airwave', '0010_auto_20191219_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirwaveCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=20, null=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('particulars', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cheque_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('online_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wallet_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=25, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('online_portal', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet_name', models.CharField(blank=True, max_length=10, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'airwave_collection',
                'managed': False,
            },
        ),
    ]
